name: Package Publish

on:
  push:
    branches: [main]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'chore(release): publish')"
    runs-on: ubuntu-latest
    name: Build/Deploy
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: git config --global user.email ${{ secrets.GH_EMAIL }}
      - run: git config --global user.name ${{ secrets.GH_USER }}
      - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.TOKEN }}" >> ~/.npmrc
      - run: npm install
      - run: npm run build
      - run: npm run publish
